import "./ThreatOverview.css";

import {
  ShieldAlert,
  ShieldCheck,
  Shield,
  TriangleAlert,
  TrendingUp,
  Activity,
} from "lucide-react";

function ThreatOverview() {

  const threats = [
    {
      level: "Critical",
      value: 2,
      width: "18%",
      color: "critical",
    },
    {
      level: "High",
      value: 5,
      width: "35%",
      color: "high",
    },
    {
      level: "Medium",
      value: 11,
      width: "60%",
      color: "medium",
    },
    {
      level: "Low",
      value: 28,
      width: "92%",
      color: "low",
    },
  ];

  return (

    <section className="threat-overview">

      <div className="threat-header">

        <div>

          <span className="threat-subtitle">

            <Activity size={16} />

            LIVE THREAT ANALYSIS

          </span>

          <h2>Threat Intelligence Overview</h2>

          <p>
            Real-time security posture generated by PatchForge AI.
          </p>

        </div>

        <div className="threat-score">

          <div className="score-circle">

            <h1>87</h1>

            <span>/100</span>

          </div>

          <small>Security Score</small>

        </div>

      </div>

      <div className="severity-list">

        {threats.map((item) => (

          <div className="severity-item" key={item.level}>

            <div className="severity-info">

              {item.level === "Critical" && <ShieldAlert size={20} />}
              {item.level === "High" && <TriangleAlert size={20} />}
              {item.level === "Medium" && <Shield size={20} />}
              {item.level === "Low" && <ShieldCheck size={20} />}

              <span>{item.level}</span>

            </div>

            <div className="severity-progress">

              <div
                className={`severity-fill ${item.color}`}
                style={{ width: item.width }}
              ></div>

            </div>

            <strong>{item.value}</strong>

          </div>

        ))}

      </div>

      <div className="ai-risk">

        <div>

          <h4>AI Risk Assessment</h4>

          <p>
            Moderate Risk • Patch generation recommended
          </p>

        </div>

        <div className="risk-badge">

          <TrendingUp size={18} />

          MODERATE

        </div>

      </div>

    </section>

  );

}

export default ThreatOverview;